apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: goodreadsprizer
  labels:
    app: backend
spec:
  replicas: 1
  selector:
      matchLabels:
        app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsUser: 1000 # Non-root user
      containers:
        - name: backend
          image: lseeger/goodreadsprizerbe:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: DB_NAME
            - name: RABBIT_MQ_URL
              value:  "amqp://guest:guest@rabbitmq.rabbitmq-system.svc.cluster.local:5672"
            - name: COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: COGNITO_USER_POOL_ID
            - name: COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: COGNITO_CLIENT_ID
            - name: COGNITO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: COGNITO_CLIENT_SECRET
            - name: COGNITO_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: COGNITO_REDIRECT_URI
            - name: COGNITO_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: COGNITO_DOMAIN
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: AWS_DEFAULT_REGION
            - name: LOGIN_URL
              valueFrom:
                secretKeyRef:
                  name: kubesecret
                  key: LOGIN_URL
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: configlocal
                  key: PUBLIC_FRONTEND_URL
            - name: PUBLIC_FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: configlocal
                  key: PUBLIC_FRONTEND_URL
            - name: PRICEALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: configlocal
                  key: PRICEALGORITHM
            - name: PUPPETEER_EXECUTABLE_PATH
              value: "/usr/bin/google-chrome"
          resources:
            limits:
              memory: "1000Mi"
              cpu: ".5"
