apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: goodreadsprizer
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP             
      port: 3000
      targetPort: 3000
      nodePort: 30005