version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: my-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: devpassword123
      POSTGRES_USER: devuser
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
  backend:
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST : postgres
  frontend:
    image: frontend-goodreadsprizer
    ports:
      - "3001:3001"
  scrapper:
    image: storescrapper

volumes:
  postgres_data: