apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: goodreadsprizer
  labels:
    app: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
          app: frontend
    template:
        metadata:
          labels:
              app: frontend
        spec:
          containers:
            - name: frontend
              image: lseeger/goodreadsprizerfe:latest
              ports:
              - containerPort: 80
              env:
                - name: SERVER_URL
                  value: http://localhost:30005/
                - name: COGNITO_REDIRECT_URI
                  valueFrom:
                    secretKeyRef:
                      name: kubesecret
                      key: COGNITO_REDIRECT_URI
                - name: COGNITO_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: kubesecret
                      key: COGNITO_DOMAIN
                - name: COGNITO_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: kubesecret
                      key: COGNITO_CLIENT_ID