apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: goodreadsprizer
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  claimRef:
    name: postgres-volume-claim
    namespace: goodreadsprizer
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql