kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: hostpath
  namespace: goodreadsprizer
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer